POST http://localhost:8080/api/payments
Accept: application/json
Content-Type: application/json

{
  "requestId": 1,
  "value": "200 PLN"
}

###

GET http://localhost:8080/api/payments/0b331c7a-df35-4eb2-8f2a-8e7d4d1g6843
Accept: application/json
Content-Type: application/json

###

GET http://localhost:8080/api/payments/started?pageNumer=0
Accept: application/json
Content-Type: application/json
