POST http://localhost:8080/api/payments
Accept: application/json
Content-Type: application/json

{
  "requestId": 1,
  "value": "200 PLN"
}

###

GET http://localhost:8080/api/payments/f45
Accept: application/json
Content-Type: application/json

###

GET http://localhost:8080/api/payments/started?pageNumer=0
Accept: application/json
Content-Type: application/json

###

###

POST http://localhost:8080/api/orders
Accept: application/json
Content-Type: application/json

{
  "entries": [
    {
      "productId": 1,
      "value": 200,
      "quantity": 3
    }
  ]
}

###

GET http://localhost:8080/api/orders/638772d76a321d72b8fb7887
Accept: application/json
Content-Type: application/json
