POST http://localhost:8080/api/payments
Accept: application/json
Content-Type: application/json

{
  "requestId": 1,
  "value": "200 PLN"
}

###

GET http://localhost:8080/api/payments/f45a6394-94c3-4909-8f08-be5b2b017db8
Accept: application/json
Content-Type: application/json

###

GET http://localhost:8080/api/payments/started?pageNumer=0
Accept: application/json
Content-Type: application/json
